builders:
  query_params:
    import: "package:dark_router/query_params_builder/query_params_builder.dart"
    builder_factories: ["queryParamsBuilder"]
    build_extensions: { ".dart": [".query_params.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
